services:
  gateway:
    image: gateway
    build:
      context: ./gateway
      dockerfile: dockerfile
    volumes:
      - ./gateway:/gateway
    ports:
      - "3000:3000"
    command: npm run dev

  ms-python:
    image: ms-python
    build:
      context: ./ms-python
      dockerfile: dockerfile
    volumes:
      - ./ms-python:/ms-python
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1